### ISSUE TITLE
Add option for fast search

### ISSUE THREAD

**Issue by belozer** [zxqfox/gather-reverse-deps#7]
```
page → content → form → input
page → search → input
page → sidebar → input
```
`gather-reverse-deps input *.blocks/ --fast`

result
```
form
search
sidebar
```

**Comment by qfox** [comment]
what about `content` and `input`?

upd: ah, you asking for one level look, it would not be `fast` for current realization because it reads full graph before going to walk through nodes. No sense to prevent walking through nodes in memory for speed, but probably it's needed to find direct dependents

**Comment by belozer** [comment]
@zxqfox  In General, it is adjacent to https://github.com/zxqfox/gather-reverse-deps/issues/6

**Comment by belozer** [comment]
The current implementation is cool, which displays all side effects. But sometimes you need to get more accurate information.
